# Generated by Django 3.0.7 on 2021-10-15 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name': 'Идею', 'verbose_name_plural': 'Идеи'},
        ),
        migrations.CreateModel(
            name='Commets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Текст комментария')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ideas')),
            ],
        ),
    ]
