# Generated by Django 3.0.7 on 2021-10-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211015_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commets',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name': 'идею', 'verbose_name_plural': 'Идеи'},
        ),
    ]
