# Generated by Django 3.0.7 on 2021-10-19 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20211015_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commets',
            new_name='Comments',
        ),
    ]
