# Generated by Django 3.0.7 on 2021-11-06 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20211022_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('completed', models.BooleanField(verbose_name='Проект выполнен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage_of_PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('description', models.TextField(verbose_name='Описание этапа')),
                ('completed', models.BooleanField(verbose_name='Этап выполнен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonalProject')),
            ],
        ),
        migrations.CreateModel(
            name='Task_of_PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='Задача')),
                ('completed', models.BooleanField(verbose_name='Задача выполнена')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stage_of_PersonalProject')),
            ],
        ),
    ]
