# Generated by Django 3.0.7 on 2021-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personalproject_stage_of_personalproject_task_of_personalproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalproject',
            options={'verbose_name': 'личный проект', 'verbose_name_plural': 'Личные проекты'},
        ),
        migrations.AlterModelOptions(
            name='stage_of_personalproject',
            options={'verbose_name': 'этап личного проекта', 'verbose_name_plural': 'Этапы личных проектов'},
        ),
        migrations.AlterModelOptions(
            name='task_of_personalproject',
            options={'verbose_name': 'задача личного проекта на текущем этапе', 'verbose_name_plural': 'Задачи личного проекта на текущем этапе'},
        ),
        migrations.AlterField(
            model_name='task_of_personalproject',
            name='task',
            field=models.CharField(max_length=500, verbose_name='Задача'),
        ),
    ]
