# Generated by Django 3.0.7 on 2021-11-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211111_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_of_personalproject',
            old_name='task',
            new_name='name',
        ),
    ]
