# Generated by Django 3.0.7 on 2021-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211127_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_of_personalproject',
            name='completed',
        ),
    ]
