# Generated by Django 3.0.7 on 2021-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_stage_of_personalproject_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_of_personalproject',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Этап выполнен'),
            preserve_default=False,
        ),
    ]
