# Generated by Django 3.0.7 on 2021-12-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211211_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_of_personalproject',
            options={'verbose_name': 'задача личного проекта на текущем этапе', 'verbose_name_plural': 'Задачи личного проекта на текущем этапе'},
        ),
        migrations.CreateModel(
            name='Task_of_TeamProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Задача')),
                ('completed', models.BooleanField(verbose_name='Задача выполнена')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stage_of_PersonalProject')),
            ],
            options={
                'verbose_name': 'задача командного проекта на текущем этапе',
                'verbose_name_plural': 'Задачи командных проекта на текущем этапе',
            },
        ),
    ]
